runtime: go
env: flex
service: emails
api_version: go1

manual_scaling:
  instances: 1

env_variables:
  SENDGRID_API_KEY: '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'
  SENDGRID_INTERNAL_API_KEY: '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'
  GOOGLEAUTHKEY: '66057093659-gdof2fgsc2j1e9v3ugkt5uvkek669ael.apps.googleusercontent.com'
  GOOGLEAUTHSECRET: 'JLJLL4sV8nse8AyW8qE5zxnu'
  OUTLOOKAUTHKEY: '6c99490b-7d78-4810-baa1-e9f7ff6b2e85'
  OUTLOOKAUTHSECRET: 'ofwJZJWE84idqpqfZwKBsEF'