application: newsai-1166
version: 1
runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app
  
env_variables:
  GOOGLEAUTHKEY: '66057093659-gdof2fgsc2j1e9v3ugkt5uvkek669ael.apps.googleusercontent.com'
  GOOGLEAUTHSECRET: 'JLJLL4sV8nse8AyW8qE5zxnu'
