application: newsai-1166
version: 1
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /.*
  script: _go_app
  secure: always

env_variables:
  GOOGLEAUTHKEY: '66057093659-gdof2fgsc2j1e9v3ugkt5uvkek669ael.apps.googleusercontent.com'
  GOOGLEAUTHSECRET: 'JLJLL4sV8nse8AyW8qE5zxnu'
  SECRETKEY: 'Cab7MNoPdBdX%fxN?yg3yWVM4^7KecETjfem6HwXizQqZTsG4#'
  CSRFKEY: '4LaCHxT6qwvDovNCb8^TXmymn^Vcxx'
  SECRETSALT: 'wsgAN6KkGKthcABExraWbBgr3^3yj,M3ppEd8}MpdypV[LavR8MjWJracUNjaxWQRvH6guWXrssP4vfU*qqiwjkwsE*3t'
  SENDGRID_KEY: 'EswwpT3vxR9i6,]yzpQP'

inbound_services:
- mail